theme: 
  - osuny
  - osuny-plugin-centered-header
  - osuny-plugin-centered-footer
_merge: deep
params:
  summary:
    position: hero
  search:
    active: true
  logo:
    header: '/assets/images/logo.png'
    footer: '/assets/images/logo-black.png'
  home:
    head:
      title: site
  breadcrumb:
    position: after-hero

  events:
    index:
      options:
        place: true

  posts:
    index:
      layout: grid